name: CI-CD Autopartss

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["main"]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        working-directory: backend
        run: |
          python manage.py test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/autopartss:${{ github.sha }}
    sonarcloud:
        needs: build_test
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request' && github.base_ref == 'main'

        steps:
        - uses: actions/checkout@v4
        with:
        fetch-depth: 0

        - name: Set up Java (SonarCloud necesita Java)
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '17'

            - name: SonarCloud Scan
        # Acción oficial de SonarCloud
                uses: SonarSource/sonarcloud-github-action@v2
                env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                SONAR_ORG: ${{ secrets.SONAR_ORG }}
                SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
  snyk_scan:
    needs: build_test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.base_ref == 'main'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image for Snyk
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: autopartss-snyk:pr

      - name: Run Snyk Container test
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: autopartss-snyk:pr
          args: --severity-threshold=high
      

  push_image:
    needs: build_test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || (github.event_name == 'pull_request' && github.base_ref == 'main')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3<
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/autopartss:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/autopartss:${{ github.sha }}

  dependency_review:
    needs: build_test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: critical

  codeql_analysis:
    needs: build_test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.base_ref == 'main'
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  docker_scout:
    needs: build_test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.base_ref == 'main'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image for Scout
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: autopartss-scout:pr

      - name: Docker Scout CVE Scan
        uses: docker/scout-action@v1
        with:
          image: autopartss-scout:pr
          command: cves
          only-severity: critical
          exit-code: '1'
